# Generated by Django 4.2.2 on 2024-06-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0002_alter_habit_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="place",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Место выполнения"
            ),
        ),
    ]
