# Generated by Django 4.2.2 on 2024-06-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0003_alter_habit_place"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="duration",
            field=models.DurationField(
                default=None, verbose_name="Продолжительность выполнения"
            ),
        ),
    ]
