# Generated by Django 4.2.2 on 2024-06-29 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0006_alter_habit_number_of_executions"),
    ]

    operations = [
        migrations.RenameField(
            model_name="habit",
            old_name="user",
            new_name="creator",
        ),
    ]
